baseurl: "" # the subpath of your site, e.g. /blog
title: ""
url: "gerodev.netlify.app" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Rosten98
github_username:  Rosten98

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
